### ISSUE TITLE
Voila: 2 kernels per dashboard

### ISSUE THREAD

**Issue by fcollonval** [ideonate/cdsdashboards#11] opened 2020-06-26 14:43 UTC
**Describe the bug**

When launching a voila dashboard server, 2 jupyter kernel process are created. I don't know if this is related to this project or to voila itself.

```
fcollon+   455  9.0  0.3 787552 113316 ?       Sl   14:39   0:01 python3 -m voila /srv/userspace/fcollonval/Presentation.ipynb --port=42309 --no-browser --Voila.base_url=/user/fcollonval/dash-demo-2/ --Voila.server_url=/ --template=axt-material
fcollon+   468 13.6  0.3 1174500 122664 ?      Ssl  14:39   0:02 /opt/conda/bin/python -m ipykernel_launcher -f /tmp/voila_r5ji1acz/kernel-5a8782af-3327-4216-8441-55c0455686b2.json
fcollon+   476 12.8  0.3 1174496 110708 ?      Ssl  14:39   0:02 /opt/conda/bin/python -m ipykernel_launcher -f /tmp/voila_r5ji1acz/kernel-922ddf42-5c12-417f-a154-005dad8eb086.json
fcollon+   484  1.8  0.1 797816 42744 ?        Ssl  14:39   0:00 python3 -m jhsingle_native_proxy.main --destport=0 python3 {-}m voila {presentation_path} {--}port={port} {--}no-browser {--}Voila.base_url={base_url}/ {--}Voila.server_url=/ --presentation-path=/srv/userspace/fcollonval/Presentation.ipynb --port=57519 {--}template=default
fcollon+   542  8.5  0.3 784940 116160 ?       Sl   14:39   0:01 python3 -m voila /srv/userspace/fcollonval/Presentation.ipynb --port=39029 --no-browser --Voila.base_url=/user/fcollonval/dash-demo/ --Voila.server_url=/ --template=default
fcollon+   566 15.1  0.3 1174500 110344 ?      Ssl  14:39   0:02 /opt/conda/bin/python -m ipykernel_launcher -f /tmp/voila_xr_2blkv/kernel-59f73e48-ea8d-40a0-9451-a14e388bd4ba.json
fcollon+   574 14.4  0.3 1174492 110912 ?      Ssl  14:39   0:02 /opt/conda/bin/python -m ipykernel_launcher -f /tmp/voila_xr_2blkv/kernel-5f7a8664-d400-4149-be4e-c2c2b55f4de0.json
```
**To Reproduce**

1. Start a voila dashboard
2. Execute : `ps auww` on the server machine

**Screenshots**

N/A

**Configuration**

```
c.JupyterHub.spawner_class = 'cdsdashboards.hubextension.spawners.VariableLocalProcessSpawner'
```

**Comment by fcollonval** [comment] 2020-06-26 14:51
Follow-up, if kernel culling is set, one of the two kernels get killed.

**Comment by danlester** [comment] 2020-06-26 15:11
I think the problem is actually that jhsingle-native-proxy is failing to kill its Voila process when it exists.

In fact, you have two Voila processes running, for two different dashboards: one for /dash-demo/ and one for /dash-demo2/.

But there is only one jhsingle-native-proxy process running, presumably because the other one has died (but left its voila process running).

Perhaps Voila manages to stop properly soon enough when it has kernel culling enabled, for some reason.

I'll take a look next week anyway. Thanks for reporting.

**Comment by danlester** [comment] 2020-08-24 14:42
I didn't observe any similar problems at least for a long-running Voila Dashboard under normal use, so I'll close this issue for now. Anyone is welcome to reopen it if they believe there is a specific problem where something isn't being killed when it should be etc.

**Closed by danlester** 2020-08-24 14:42 UTC
Labels: bug
